### PR TITLE
Unresolved type during parsing: net.openhft.affinity.Affinity when on MacOS

### PR DESCRIPTION
**Pull request by ffang**
… mac in native mode 

fixes: #189

### CODE REVIEW

**Comment by pivovarit** [comment]
Sorry for being so slow on this. I'm currently on vacation and will pick this up when I'm back on Thursday

**Comment by ppalaga** [comment]
No problem, enjoy your vacation, @pivovarit!

**Comment by pivovarit** [comment]
@ffang please sign our CLA ([link](https://github.com/hazelcast/quarkus-hazelcast-client/pull/190#issuecomment-864111125)), I can't merge without i

**Comment by ffang** [comment]
> @ffang please sign our CLA ([link](https://github.com/hazelcast/quarkus-hazelcast-client/pull/190#issuecomment-864111125)), I can't merge without it

Hi @pivovarit ,

CLA signed.

Thanks for your help!
Freeman

**Review by pivovarit — APPROVED** [review]

**Comment by pivovarit** [comment]
Thanks @ffang and @ppalaga - releasing as soon we get the release approval for the new major version.

**Comment by ffang** [comment]
Thanks a lot @pivovarit !

**Pull request merged**
