### PR TITLE
Upgrade to Quarkus 2.0.0.Final

### PR DESCRIPTION
**Pull request by ppalaga**

### CODE REVIEW

**Comment by ppalaga** [comment]
Any plans to release a Quarkus 2.0.0.Final based release, @pivovarit ?

**Review by pivovarit — APPROVED** [review]

**Comment by pivovarit** [comment]
@ppalaga we'll test and release asap

**Comment by pivovarit** [comment]
@ppalaga the extension is released. Do I also need to issue a PR against `quarkus-platform`?

**Comment by ppalaga** [comment]
> Do I also need to issue a PR against `quarkus-platform`?

Yes, please do so as soon as possible. They are releasing as we speak.

**Pull request merged**
